---
loadGenerator:
  apiClientId: YOUR_API_CLIENT_ID
  apiClientSecret: YOUR_API_CLIENT_SECRET
  projectKey: YOUR_PROJECT_KEY
suites:
  50 users for 5 mins:
    concurrency: 50
    delay: 0s
    duration: 5m
    rampUp: 1m
    rampDown: 30s
    steps:
      Open landing page and await to be loaded:
        - open: https://verifications.perforator.io/
        - awaitElementToBeVisible: '#async-container'
      Verify page 1:
        - click: ul.navbar-nav li:nth-child(1) a
        - awaitElementToBeVisible: '#async-container'
      Verify page 2:
        - click: ul.navbar-nav li:nth-child(2) a
        - awaitElementToBeVisible: '#async-container'